repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        exclude: ^(.*\.(lock|cache|bin|exe|so|dylib|ipynb))$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^(.*\.(lock|cache|bin|exe|so|dylib|ipynb))$
      - id: ruff-format
        exclude: ^(.*\.(lock|cache|bin|exe|so|dylib|ipynb))$

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
        pass_filenames: false
        args: ["src"]

      - id: pylint
        name: pylint
        entry: uv run pylint
        language: system
        types: [python]
        args: ["src"]
