name: CI

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync

      - name: Run Ruff Check
        run: uv run ruff check .

      - name: Run Ruff Format Check
        run: uv run ruff format . --check

      - name: Run MyPy
        run: uv run mypy src

      - name: Run PyLint
        run: uv run pylint src

  test:
    name: Testing
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: uv sync

      - name: Run Tests
        run: uv run pytest tests/ -v
